config/routes.rb
MediNet::Application.routes.draw do
  match "profil/:id/:slug" => 'profil#show',  :as => "profil"
  match "profil/edit" => 'profil#edit',       :as => "edit_profil"
  match "profil/auth" => 'profil#auth',       :as => "auth_profil"
  match "profil/import" => 'profil#import',   :as => "import_profil"
  
  root :to => 'welcome#index'
  
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :firstname, :lastname, :headline, :picture_url
  
  def fullname
    "#{firstname} #{lastname}"
  end
  
  def slug
    fullname.parameterize
  end
  
  def update_from_linkedin(client_ready)    
    
    client_ready.profile(:fields => ["first_name", "last_name", "headline", "picture-url"]).tap do |profil| 
      self.firstname = profil.first_name
      self.lastname = profil.last_name
      self.headline = profil.headline 
      self.picture_url = profil.picture_url
    end
    
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profil_controller.rb
# encoding: UTF-8

class ProfilController < ApplicationController
  before_filter :get_user, :except => :show
  
  def show
    @user = User.find params[:id]
  end

  def edit
    if params[:user]
      @user.update_attributes(params[:user])
      redirect_to profil_path(@user.id, @user.slug), :notice => "Profil édité avec succès"
    end
  end

  def auth
    client = get_client
    
    request_token = client.request_token(:oauth_callback => import_profil_url)
    session[:rtoken]  = request_token.token
    session[:rsecret] = request_token.secret
    
    redirect_to client.request_token.authorize_url
  end
  
  def import
    client = get_client
    
    if session[:rtoken].nil?
      render :action => :auth
    else
      pin_code = params[:oauth_verifier]
      atoken, asecret = client.authorize_from_request(params[:oauth_token], session[:rsecret], pin_code)
      
      session[:rtoken]  = atoken
      session[:rsecret] = asecret
      
      @user.update_from_linkedin(client)
      
      redirect_to profil_path(@user.id, @user.slug), :notice => "Informations importées avec succès"
    end
  end
  
  private
    def get_user
      @user = User.find session[:user_id]
    end
    
    def get_client
      LinkedIn::Client.new(APP_CONFIG['api_key'], APP_CONFIG['api_secret'])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    user = User.first
    session[:user_id] = user.id
    redirect_to profil_path(user.id, user.slug)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediNet</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">MediNet</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container main">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>Yeah !</strong> <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>Oulaa !</strong> <%= flash[:alert] %>
      </div>
    <% end %>
    
    <%= yield %>
  </div> <!-- /container -->

</body>
</html>

app/views/profil/edit.html.erb
<h1>Editer le profil</h1>

<%= form_for @user, :as => :user, :url => edit_profil_path(@user.id) do |f| -%>
  <div>
    <strong>Photo : </strong><%= image_tag @user.picture_url, :alt => "Photo de profil", :class => "picture" if @user.picture_url? %> <%= f.text_field :picture_url %>
  </div>

  <dl>
    <dt>Nom :</dt>
    <dd><%= f.text_field :lastname %></dd>
  
    <dt>Prénom :</dt>
    <dd><%= f.text_field :firstname %></dd>
  
    <dt>Poste actuel :</dt>
    <dd><%= f.text_field :headline %></dd>
  </dl>

  <%= submit_tag "Enregistrer", :id => "submit", :name => "submit", :class => "btn btn-primary", :disabled => false, :disable_with => "Une seconde..." %>
<% end %>

app/views/profil/import.html.erb
<%= debug @profile %>

app/views/profil/show.html.erb
<h1>Salut <%= @user.firstname %> !</h1>

<%= image_tag @user.picture_url, :alt => "Photo de profil", :class => 'picture right' if @user.picture_url? %>

<div><%= @user.headline %></div>

<dl>
  <dt>Nom :</dt>
  <dd><%= @user.lastname %></dd>
  
  <dt>Prénom :</dt>
  <dd><%= @user.firstname %></dd>
</dl>

<a href="<%= edit_profil_path %>" class="btn btn-danger">Editer le profil</a>
<a href="<%= auth_profil_path %>" class="btn btn-success">Mettre à jour à partir de LinkedIn</a>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>